### ISSUE TITLE
Zulip Id Key Error from POST request on /api/info/

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-backend#54]
### Describe the bug
When a new user registers from open-source-programs-frontend and tries to edit information on dashboard the Django server respond with internal server error(500).
The Error is as follows:
```
[27/Jan/2021 17:24:22] "POST /api/info/ HTTP/1.1" 500 18345
[27/Jan/2021 17:24:25] "GET /api/info/ HTTP/1.1" 200 2
[27/Jan/2021 17:24:25] "GET /api/user/ HTTP/1.1" 200 80
[27/Jan/2021 17:24:25] "GET /api/info/ HTTP/1.1" 200 2
[27/Jan/2021 17:24:25] "GET /api/info/ HTTP/1.1" 200 2
Internal Server Error: /api/info/
Traceback (most recent call last):
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sankalp/Desktop/open-source-programs-backend/venv/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/sankalp/Desktop/open-source-programs-backend/osp/views/user_information.py", line 30, in create
    response = get_zulip_user(request.data['zulip_id'])
KeyError: 'zulip_id'
```

### To Reproduce
One way:
1. Make a POST request on http://127.0.0.1:8000/api/info/ by removing the zulip_id field as it is not a required field.
2. Server responds with an 500 response.

Another way:
1. Register through the frontend.
2. Try to LOGIN using the frontend.
3. Now try to complete fill your profile data the server responds with 500 internal server errors.

### Expected behavior
See the attached screenshot.

### Screenshots
![image](https://user-images.githubusercontent.com/56037184/106031754-a2d42c00-60f5-11eb-93a3-b43be3971ac2.png)

### Desktop (please complete the following information):
 - OS: Ubuntu
 - Browser: Chrome
 - Version - __

**Comment by codesankalp** [comment]
I created this issue due to this conversation: https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs/topic/Questions/near/224155459
I think this needs to be handled carefully as zulip_id key is not present in request.data
https://github.com/anitab-org/open-source-programs-backend/blob/7ed23865db35e3e3ef6d1b3d3b80695b0f2103e3/osp/views/user_information.py#L30

@isabelcosta Is this issue seems to be valid or should I close this?

**Comment by codesankalp** [comment]
In UserInformation model
https://github.com/anitab-org/open-source-programs-backend/blob/7ed23865db35e3e3ef6d1b3d3b80695b0f2103e3/osp/models/user_information.py#L20

`blank=True` we should use either a default value for validation purpose because when zulip_id is not in response we have to keep it null or try to give it a default value?

**Comment by codesankalp** [comment]
https://github.com/anitab-org/open-source-programs-backend/blob/7ed23865db35e3e3ef6d1b3d3b80695b0f2103e3/osp/migrations/0014_auto_20200824_1924.py#L18

In the migration file default value is 1, so either we should also provide the default value in models, or make it null=True.

**Comment by codesankalp** [comment]
https://github.com/anitab-org/open-source-programs-web/pull/51
This error will be addressed after merging this pull request.
So closing this issue.
